default:
  dirs:
    library: !expr system.file("extdata", package = "OpenSpecy")
    appdata: !expr system.file("shiny", "data", package = "OpenSpecy")

shinyapps:
  dirs:
    library: 'data/'
    appdata: 'data/'
